name: E2E Testing
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
on:
  pull_request:
    types: [opened, synchronize, reopened]
concurrency:
  group: react-native-workflow-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_android:
    name: Build & Test Android
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          check-latest: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run Yarn Install
        run: yarn install

      - name: Build Release APK
        run: cd android && ./gradlew assembleRelease && find . -type f -name "*.apk"

      - name: Upload to Maestro Cloud
        uses: mobile-dev-inc/action-maestro-cloud@v1.8.0
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: app/build/outputs/apk/release/app-release.apk

  build_ios:
    name: Build IOS
    timeout-minutes: 60
    runs-on: macos-latest
    steps:
      - name: Archive iOS app
        run: echo "To be implemented"
#    - uses: actions/checkout@v2
#    - uses: maxim-lobanov/setup-xcode@v1.6.0
#      with:
#        xcode-version: 14.2.0
#    - run: cd ios && xcodebuild -project reactnativetesting.xcodeproj -scheme reactnativetesting -destination 'platform=iOS Simulator,name=iPhone 11'
