name: E2E Testing
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
on:
  pull_request:
    types: [opened, synchronize, reopened]
concurrency:
  group: react-native-workflow-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_android:
    name: Build Android
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          check-latest: true
      - name: Save Keystore Credentials
        working-directory: /home/runner/work
        run: |
          ls -la
          touch gradle.properties
          echo RN_TESTING_APP_UPLOAD_STORE_FILE=${{ secrets.RN_TESTING_APP_UPLOAD_STORE_FILE }} > gradle.properties
          echo RN_TESTING_APP_UPLOAD_KEY_ALIAS=${{ secrets.RN_TESTING_APP_UPLOAD_KEY_ALIAS }} >> gradle.properties
          echo RN_TESTING_APP_UPLOAD_STORE_PASSWORD=${{ secrets.RN_TESTING_APP_UPLOAD_STORE_PASSWORD }} >> gradle.properties
          echo RN_TESTING_APP_UPLOAD_KEY_PASSWORD=${{ secrets.RN_TESTING_APP_UPLOAD_KEY_PASSWORD }} >> gradle.properties
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Build Release APK
        run: ./gradlew assembleRelease

  test_android:
    name: Test Android
    needs: build_android
    runs-on: macos-latest
    steps:
      - uses: mobile-dev-inc/action-maestro-cloud@v1.8.0
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: app/build/outputs/apk/release/app-release.apk


#  build_ios:
#    name: Build IOS
#    timeout-minutes: 60
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - uses: actions/setup-xcode@v2
#      with:
#        xcode-version: 15
#    - run: xcodebuild -project MyApp.xcodeproj -scheme MyApp -destination 'platform=iOS Simulator,name=iPhone 11'
#
#  test_ios:
#    name: Test Android
#    needs: build_android
#    runs-on: macos-latest
#    steps:
#      - uses: mobile-dev-inc/action-maestro-cloud@v1.8.0
#        with:
#          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
#          app-file: app/build/outputs/apk/release/app-release.apk
